kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: ingress-altdemo
  namespace: altdemo
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/backend-protocol: HTTP
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: 16m
spec:
  tls:
  - hosts:
    - azure-load-testing-demo-beefy.westeurope.cloudapp.azure.com
    # secretName: {{Kubernetes Secret name with TLS/SSL Certificate}}
  rules:
  - host: azure-load-testing-demo-beefy.westeurope.cloudapp.azure.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: altdemo
            port:
              number: 8080