name: Load Test with ALT
on: [push]

env:
  AZURE_WEBAPP_NAME: "http://azure-load-testing-demo-beefy.westeurope.cloudapp.azure.com"    # set this to your application's name
  LOAD_TEST_RESOURCE: "alt-demo"
  LOAD_TEST_RESOURCE_GROUP: "rg-loadtesting-demo"

jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    steps:

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: 'Azure Load Testing'
      uses: azure/load-testing@v1
      with:
        loadTestConfigFile: 'load-test-config.yaml'
        loadTestResource: ${{ env.LOAD_TEST_RESOURCE }}
        resourceGroup: ${{ env.LOAD_TEST_RESOURCE_GROUP }}
        env: |
          [
            {
            "name": "webapp",
            "value": "${{ env.AZURE_WEBAPP_NAME }}"
            }
          ]