name: Load Test with ALT
on: [push]

jobs:
  deploy-environment:
    runs-on: ubuntu-latest
    steps:

    - name: Log in with Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Azure Deployment Environment(ADE) - Create environment
      uses: azure/CLI@v1
      with:
        azcliversion: 2.45.0
        inlineScript: |
          az extension add --name devcenter --yes
          az devcenter dev environment create \
              --dev-center-name dc-devx \
              --project-name the-phoenix-project \
              --environment-name workflow-webapp-ephemeral \
              --environment-type sandbox \
              --catalog-item-name FunctionApp \
              --catalog-name  CommunityTemplates